from .load_licensed_repositories_to_bq import LoadLicensedRepositoriesToBQAction
from .load_companies_contrib_repos_to_bq import LoadCompaniesContribReposToBQAction
from .load_osci_commits_ranking_to_bq import LoadOSCICommitsRankingToBQAction
from .load_osci_ranking_to_bq import LoadOSCIRankingToBQAction
from .load_push_events_to_bq import LoadPushEventTOBQAction
from .transfer_to_web import TransferMonthlyChangeRankingAction
