/* Copyright since 2019, EPAM Systems

   This file is part of OSCI.

   OSCI is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   OSCI is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with OSCI.  If not, see <http://www.gnu.org/licenses/>.
*/


IF OBJECT_ID('Actors', 'U') IS NULL CREATE TABLE Actors (
	 ActorId BIGINT
	,ActorLogin NVARCHAR(250) NULL
	,ActorUrl NVARCHAR(250) NULL
	);

IF OBJECT_ID('Repositories', 'U') IS NULL CREATE TABLE Repositories (
	 Id BIGINT
	,RepoName NVARCHAR(250) NULL
	,RepoUrl NVARCHAR(250) NULL
	,OrgId BIGINT NULL
	);

IF OBJECT_ID('Organizations', 'U') IS NULL CREATE TABLE Organizations (
	 Id BIGINT
	,OrgName NVARCHAR(250) NULL
	,OrgUrl NVARCHAR(250) NULL
	);

IF OBJECT_ID('GitEvents', 'U') IS NULL CREATE TABLE GitEvents (
	 EventId BIGINT
	,EventType NVARCHAR(50)
	,EventCreated DATETIME2(7)
	,RepoId BIGINT
	,ActorId BIGINT
	,OrgId BIGINT NULL
	);

IF OBJECT_ID('GitCommits', 'U') IS NULL CREATE TABLE GitCommits (
	 GitEventId BIGINT
	,RepoId BIGINT
	,Sha NVARCHAR(100) NULL
	,AuthorName NVARCHAR(250) NULL
	,AuthorMailDomain NVARCHAR(250) NULL
	);

IF OBJECT_ID('OrganizationsNames', 'U') IS NULL
BEGIN
    CREATE TABLE OrganizationsNames(
         OrgName nvarchar(250)
        ,OrgDomain nvarchar(250)
        );

    INSERT INTO OrganizationsNames(OrgName, OrgDomain)
    VALUES
    ('4teamwork', '4teamwork.ch'),
    ('5minds', '5minds.de'),
    ('AMD', 'amd.com'),
    ('ARM', 'arm.com'),
    ('ATHiNA', 'athina.co.nz'),
    ('Accenture', 'accenture.com'),
    ('Acsone', 'acsone.eu'),
    ('Ad Hoc', 'adhocteam.us'),
    ('Adguard', 'adguard.com'),
    ('Adobe', 'adobe.com'),
    ('Agaric', 'agaric.com'),
    ('Alauda.io', 'alauda.io'),
    ('Alfresco', 'alfresco.com'),
    ('Algolia', 'algolia.com'),
    ('Alibaba', 'alibaba-inc.com'),
    ('Amazon', 'amazon.com'),
    ('Amdocs', 'amdocs.com'),
    ('Analog Devices', 'analog.com'),
    ('Andela', 'andela.com'),
    ('Ant Financial', 'antfin.com'),
    ('Antmicro', 'antmicro.com'),
    ('Apple', 'apple.com'),
    ('ArangoDB', 'arangodb.com'),
    ('Arbisoft ', 'arbisoft.com'),
    ('Arisan', 'arisan.io'),
    ('Art Deco', 'adc.sh'),
    ('Asian Tech', 'asiantech.vn'),
    ('Atlassian', 'atlassian.com'),
    ('Atomist', 'atomist.com'),
    ('Atypon', 'atypon.com'),
    ('Autodesk', 'autodesk.com'),
    ('Automattic', 'automattic.com'),
    ('Autonomous', 'autonomous.nyc'),
    ('Azavea', 'azavea.com'),
    ('B2CK', 'b2ck.com'),
    ('BBC', 'bbc.co.uk'),
    ('BJISS', 'bjss.com'),
    ('Baidu', 'baidu.com'),
    ('Balena', 'balena.io'),
    ('Belledonne Communications', 'belledonne-communications.com'),
    ('Binary Group', 'binary.com'),
    ('Bitnami', 'bitnami.com'),
    ('Bitrise', 'bitrise.io'),
    ('Block.one', 'block.one'),
    ('Blockchain Foundry', 'blockchainfoundry.co'),
    ('Bloomberg', 'bloomberg.net'),
    ('Bootlin', 'bootlin.com'),
    ('Bosch', 'bosch.com'),
    ('Brave', 'brave.com'),
    ('Broadcom', 'broadcom.com'),
    ('Buoyant', 'buoyant.io'),
    ('Buro Happold', 'burohappold.com'),
    ('CERN', 'cern.ch'),
    ('CGI', 'cgi.com'),
    ('CKSource', 'cksource.com'),
    ('CS Group', 'c-s.fr'),
    ('Camptocamp', 'camptocamp.com'),
    ('Camunda', 'camunda.com'),
    ('Canonical', 'canonical.com'),
    ('Capgemini', 'capgemini.com'),
    ('Caser Seguros', 'caser.es'),
    ('Centreon', 'centreon.com'),
    ('Chef', 'chef.io'),
    ('CircleCI', 'circleci.com'),
    ('Cisco Systems', 'cisco.com'),
    ('Citrix ', 'citrix.com'),
    ('CloudCannon', 'cloudcannon.com'),
    ('Cloudbees', 'cloudbees.com'),
    ('Cloudera', 'hortonworks.com'),
    ('Cloudfare', 'cloudflare.com'),
    ('Cockroachlabs', 'cockroachlabs.com'),
    ('Codethink', 'codethink.co.uk'),
    ('Cognizant', 'cognizant.com'),
    ('Collabora', 'collabora.com'),
    ('Com3elles', 'com3elles.com'),
    ('Confluent', 'confluent.io'),
    ('ConsenSys', 'consensys.net'),
    ('Couchbase', 'couchbase.com'),
    ('Cozy', 'cozycloud.cc'),
    ('Ctrl', 'ctrl.nl');
    ('D2L', 'd2l.com'),
    ('D2iQ', 'mesosphere.com'),
    ('DOSarrest', 'dosarrest.com'),
    ('Datadoghq', 'datadoghq.com'),
    ('Decred', 'decred.org'),
    ('Dell', 'dell.com'),
    ('Devox Software', 'devoxsoftware.com'),
    ('Digital Asset', 'digitalasset.com'),
    ('Digital Bazaar', 'digitalbazaar.com'),
    ('Dimagi', 'dimagi.com'),
    ('Docker ', 'docker.org'),
    ('Docker', 'docker.com'),
    ('Dynamo', 'dynamo.com.uy'),
    ('Dynatrace', 'dynatrace.com'),
    ('EPAM', 'epam.com'),
    ('ESRI', 'esri.com'),
    ('East Agile', 'eastagile.com'),
    ('Eficent', 'eficent.com'),
    ('Elastic', 'elastic.co'),
    ('Enalean', 'enalean.com'),
    ('Endlessm', 'endlessm.com'),
    ('Enigio Time', 'enigio.com'),
    ('Enjin', 'enjin.com'),
    ('Equinor', 'equinor.com'),
    ('Ericsson', 'ericsson.com'),
    ('Espressif', 'espressif.com'),
    ('EuroLinux', 'euro-linux.com'),
    ('Exoplatform', 'exoplatform.com'),
    ('Experis', 'no.experis.com'),
    ('Facebook', 'fb.com'),
    ('Financial Times', 'ft.com'),
    ('Finbourne', 'finbourne.com'),
    ('Flatiron school', 'flatironschool.com'),
    ('Forestry.io', 'forestry.io'),
    ('GVEMPIRE', 'gvempire.com'),
    ('Galera Cluster', 'galeracluster.com'),
    ('GatsbyJS', 'gatsbyjs.com'),
    ('Giant Swarm', 'giantswarm.io'),
    ('GitHub', 'github.com'),
    ('GitLab', 'gitlab.com'),
    ('Gofore', 'gofore.com'),
    ('Golden Dimension', 'adorsys.com.ua'),
    ('Google', 'google.com'),
    ('Gradle', 'gradle.com'),
    ('Grafana', 'grafana.com'),
    ('Graylog', 'graylog.com'),
    ('H2O.ai', 'h2o.ai'),
    ('HERE', 'here.com'),
    ('HashiCorp', 'hashicorp.com'),
    ('Haulmont Technology', 'haulmont.com'),
    ('Hewlett Packard Enterprise', 'hpe.com'),
    ('Huawei', 'huawei.com'),
    ('IBM', 'ibm.com'),
    ('ITsyndicate', 'itsyndicate.org'),
    ('Igalia', 'igalia.com'),
    ('Improbable', 'improbable.io'),
    ('Indexdata', 'indexdata.com'),
    ('Infosiftr', 'infosiftr.com'),
    ('Infragistics', 'infragistics.com'),
    ('Innovify', 'innovify.in'),
    ('Insolar Technologies', 'insolar.io'),
    ('Instructure', 'instructure.com'),
    ('Intel', 'intel.com'),
    ('Intential', 'itential.com'),
    ('Iohk', 'iohk.io'),
    ('JTL-Software', 'jtl-software.com')
    ('JankariTech', 'jankaritech.com'),
    ('JetBrains', 'jetbrains.com'),
    ('Joyent', 'joyent.com'),
    ('Julia Computing', 'juliacomputing.com'),
    ('Kainos', 'kainos.com'),
    ('Kaltura', 'kaltura.com'),
    ('Kinvolk', 'kinvolk.io'),
    ('Kitware', 'kitware.com'),
    ('Kiwi.com', 'kiwi.com'),
    ('LG Electronics', 'lge.com'),
    ('LabKey ', 'labkey.com'),
    ('Liferay', 'liferay.com'),
    ('Lightcurve', 'lightcurve.io'),
    ('Linaro', 'linaro.org'),
    ('LinkedIn', 'linkedin.com'),
    ('Linutronix', 'linutronix.de'),
    ('Loodos Tech', 'loodos.com'),
    ('LunarG ', 'lunarg.com'),
    ('Luxoft', 'luxoft.com'),
    ('Lyft', 'lyft.com'),
    ('Lynx', 'lynxspa.com'),
    ('Made Tech', 'madetech.com'),
    ('Magento', 'magento.com'),
    ('ManpowerGroup', 'experis.com'),
    ('Mapbox', 'mapbox.com'),
    ('MariaDB', 'mariadb.com'),
    ('Maykin Media', 'maykinmedia.nl'),
    ('MediaTek', 'mediatek.com'),
    ('Mellanox Technologies', 'mellanox.com'),
    ('Mendix', 'mendix.com'),
    ('Microchip Technology', 'microchip.com'),
    ('Motion Picture', 'motionpicture.jp'),
    ('MountBlue Technologies', 'mountblue.io'),
    ('MountBlue Technologies', 'mountblue.tech'),
    ('Mozilla', 'mozilla.com'),
    ('MuleSoft', 'mulesoft.com'),
    ('NVidia', 'nvidia.com'),
    ('NXP', 'nxp.com'),
    ('Netflix', 'netflix.com'),
    ('Nevion', 'nevion.com'),
    ('New Relic', 'newrelic.com'),
    ('Nextcloud', 'nextcloud.com'),
    ('Nexylan', 'nexylan.com'),
    ('Nomandic Labs', 'nomadic-labs.com'),
    ('Nordic Semiconductor', 'nordicsemi.no'),
    ('Nuxeo' ,'nuxeo.com'),
    ('Nymea', 'nymea.io'),
    ('OCTO Technology', 'octo.com'),
    ('ONLYOFFICE', 'onlyoffice.com'),
    ('Obvious', 'obvious.in'),
    ('Odoo', 'odoo.com'),
    ('Okta', 'okta.com'),
    ('OnGres', 'ongres.com'),
    ('OpenLattice', 'openlattice.com'),
    ('Oracle', 'oracle.com'),
    ('Orange', 'orange.com'),
    ('Origin', 'originprotocol.com'),
    ('Osrfoundation' ,'osrfoundation.org'),
    ('PTFS Europe', 'ptfs-europe.com'),
    ('PTV Group', 'ptvgroup.com'),
    ('Palantir', 'palantir.com'),
    ('Palo Alto Networks', 'paloaltonetworks.com'),
    ('Pantheon', 'pantheon.io'),
    ('Percona', 'percona.com'),
    ('Pilz', 'pilz.de'),
    ('Pivotal', 'pivotal.io'),
    ('Pixel & Tonic', 'pixelandtonic.com'),
    ('Plotly', 'plot.ly'),
    ('Polidea', 'polidea.com'),
    ('Polyapp', 'polyapp.tech'),
    ('Povio', 'poviolabs.com'),
    ('Prisme.ai', 'prism.ai'),
    ('Privacy1', 'privacyone.co'),
    ('Progresssoft', 'progressoft.com'),
    ('Puppet', 'puppet.com'),
    ('Pyup', 'pyup.io'),
    ('Qt', 'qt.io'),
    ('QualityKiosk', 'qualitykiosk.com'),
    ('RStudio', 'rstudio.com'),
    ('RTE', 'rte-france.com'),
    ('Rackspace', 'rackspace.com'),
    ('ReTest', 'retest.de'),
    ('Reaktor', 'reaktor.com'),
    ('Red Hat', 'redhat.com'),
    ('Renovateapp', 'renovateapp.com'),
    ('Robotis', 'robotis.com'),
    ('Rockchip', 'rock-chips.com'),
    ('SAP', 'sap.com'),
    ('SBK Kontur', 'skbkontur.ru'),
    ('STMicroelectronics', 'st.com'),
    ('SUSE', 'suse.com'),
    ('SYSOP', 'sysop.cz'),
    ('Salesforce', 'salesforce.com'),
    ('Samsung', 'samsung.com'),
    ('Scality', 'scality.com'),
    ('ScyllaDB', 'scylladb.com'),
    ('SecOps Solutions', 'secops.in'),
    ('Sentry', 'sentry.io'),
    ('Shopify', 'shopify.com'),
    ('Shopkeep', 'shopkeep.com'),
    ('Shopsys', 'shopsys.com'),
    ('Shopware', 'shopware.com'),
    ('SiFive', 'sifive.com'),
    ('Siemens', 'siemens.com'),
    ('SignalFx', 'signalfx.com'),
    ('Silicus', 'silicus.com'),
    ('Silverstripe', 'silverstripe.com'),
    ('Snyk', 'snyk.io'),
    ('Softtek', 'softtek.com'),
    ('Softwire', 'softwire.com'),
    ('Solita ', 'solita.fi'),
    ('Sonarsource', 'sonarsource.com'),
    ('Sonymobile', 'sonymobile.com'),
    ('Sopra Steria', 'soprasteria.com'),
    ('Splunk', 'splunk.com'),
    ('Spryker', 'spryker.com'),
    ('Square', 'squareup.com'),
    ('Stripe', 'stripe.com'),
    ('SuperSoftware ', 'supersoftware.co.jp'),
    ('Switch Software', 'switch.com.uy'),
    ('Syndicode', 'syndicode.com'),
    ('Synopsys', 'synopsys.com'),
    ('T-Systems', 't-systems.com'),
    ('TI', 'ti.com'),
    ('Talan', 'talan.com'),
    ('Talend', 'talend.com'),
    ('TeamDev', 'teamdev.com'),
    ('Tencent', 'tencent.com'),
    ('Tensor', 'tensor.ru'),
    ('Test.com', 'test.com'),
    ('The Dextrous Web', 'dxw.com'),
    ('The guardian', 'guardian.co.uk'),
    ('ThoughtWorks', 'thoughtworks.com'),
    ('Toucan Toco', 'toucantoco.com'),
    ('Travis CI', 'travis-ci.org'),
    ('Truss Works', 'truss.works'),
    ('Tutanota', 'tutanota.com'),
    ('Twilio', 'twilio.com'),
    ('Twitter', 'twitter.com'),
    ('Tyro', 'tyro.com'),
    ('Uber', 'uber.com'),
    ('Uninvention', 'univention.de'),
    ('Unity Technologies', 'unity3d.com'),
    ('VMware', 'vmware.com'),
    ('VTEX', 'vtex.com.br'),
    ('Vaadin', 'vaadin.com'),
    ('Verizon Media', 'verizonmedia.com'),
    ('WIX', 'wix.com'),
    ('WSO2', 'wso2.com'),
    ('WarnerMedia', 'turner.com'),
    ('WebMob Technologies', 'webmob.tech'),
    ('Wind River', 'windriver.com'),
    ('Wipro', 'wipro.com'),
    ('Wire', 'wire.com'),
    ('WolfVision', 'wolfvision.net'),
    ('Yahoo', 'yahoo-inc.com'),
    ('Yandex', 'yandex-team.ru'),
    ('Yoast', 'yoast.com'),
    ('Yunion', 'yunionyun.com'),
    ('Zalando', 'zalando.de'),
    ('commercetools', 'commercetools.de'),
    ('datavisyn ', 'datavisyn.io'),
    ('everis', 'everis.com'),
    ('eyeo', 'adblockplus.org'),
    ('eyeo', 'eyeo.com'),
    ('feenk', 'feenk.com'),
    ('iXsystems', 'ixsystems.com'),
    ('ids', 'ids.com.mx'),
    ('itemis', 'itemis.de'),
    ('kumparan.com', 'kumparan.com'),
    ('metas', 'metasfresh.com'),
    ('mongoDB', 'mongodb.com'),
    ('mySociety', 'mysociety.org'),
    ('plentymarkets', 'plentymarkets.com'),
    ('t-matix', 't-matix.com'),
    ('tweag.io', 'tweag.io'),
    ('what.', 'what.digital'),
	('Microsoft', 'microsoft.com')

END;