meta:
  config_source: 'dbutils'
  extends: 'prod'
  databricks_scope: 'osci'
file_system:
  account_name: 'osci-blob-account-name'
  account_key: 'osci-blob-account-key'
web:
  account_name: 'osci-web-blob-account-name'
  account_key: 'osci-web-blob-account-key'
bq:
  project: 'osci-bq-project'
  secret: 'osci-bq-client-secret'
github:
  token: 'osci-gh-token'